services:
  kong-db:
    image: postgres:13
    container_name: kong-db
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD}
    volumes:
      - kong_db_data:/var/lib/postgresql/data
    networks:
      - pettopia-network

  kong-migrations:
    image: kong:latest
    container_name: kong-migrations
    depends_on:
      - kong-db
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-db"
      KONG_PG_DATABASE: "kong"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
    command: "kong migrations bootstrap"
    networks:
      - pettopia-network
    restart: on-failure

  kong-gateway:
    image: kong:latest
    container_name: kong-gateway
    depends_on:
      kong-db:
        condition: service_started
      kong-migrations:
        condition: service_completed_successfully
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-db"
      KONG_PG_DATABASE: "kong"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - pettopia-network

  konga:
    image: pantsel/konga
    container_name: konga-gui
    depends_on:
      konga-db:
        condition: service_healthy
      kong-gateway:
        condition: service_started
    environment:
      DB_ADAPTER: "postgres"
      DB_HOST: "konga-db"
      DB_PORT: 5432
      DB_USER: "konga"
      DB_PASSWORD: "konga123"
      DB_DATABASE: "konga"
    ports:
      - "1337:1337"
    networks:
      - pettopia-network
    restart: always

  konga-db:
    image: postgres:11
    container_name: konga-db
    environment:
      POSTGRES_DB: konga
      POSTGRES_USER: konga
      POSTGRES_PASSWORD: "konga123"
    volumes:
      - konga_data:/var/lib/postgresql/data
    networks:
      - pettopia-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U konga -d konga"]
      interval: 5s
      timeout: 5s
      retries: 5
  api-gateway-1:
    build:
      context: ./apps/api-gateway
      dockerfile: Dockerfile
    image: ${DOCKER_HUB}/pettopia-api-gateway:latest
    container_name: api-gateway-1
    # ports:
    #   - "3333:3000"
    env_file: apps/api-gateway/.env
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - pettopia-network

  api-gateway-2:
    build:
      context: ./apps/api-gateway
      dockerfile: Dockerfile
    image: ${DOCKER_HUB}/pettopia-api-gateway:latest
    container_name: api-gateway-2
    env_file: apps/api-gateway/.env
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis # <--- Thêm dòng này
      - REDIS_PORT=6379
    networks:
      - pettopia-network

  auth-service:
    build:
      context: ./apps/auth-service
      dockerfile: Dockerfile
    image: ${DOCKER_HUB}/pettopia-auth-service:latest
    container_name: auth-service
    env_file: apps/auth-service/.env
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - pettopia-network

  billing-service:
    build:
      context: ./apps/billing-service
      dockerfile: Dockerfile
    image: ${DOCKER_HUB}/pettopia-billing-service:latest
    container_name: billing-service
    env_file: apps/billing-service/.env
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    networks:
      - pettopia-network

  communication-service:
    build:
      context: ./apps/communication-service
      dockerfile: Dockerfile
    image: ${DOCKER_HUB}/pettopia-communication-service:latest
    container_name: communication-service
    env_file: apps/communication-service/.env
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    networks:
      - pettopia-network

  customer-service:
    build:
      context: ./apps/customer-service
      dockerfile: Dockerfile
    image: ${DOCKER_HUB}/pettopia-customer-service:latest
    container_name: customer-service
    env_file: apps/customer-service/.env
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    networks:
      - pettopia-network

  healthcare-service:
    build:
      context: ./apps/healthcare-service
      dockerfile: Dockerfile
    image: ${DOCKER_HUB}/pettopia-healthcare-service:latest
    container_name: healthcare-service
    env_file: apps/healthcare-service/.env
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    networks:
      - pettopia-network

  partner-service:
    build:
      context: ./apps/partner-service
      dockerfile: Dockerfile
    image: ${DOCKER_HUB}/pettopia-partner-service:latest
    container_name: partner-service
    env_file: apps/partner-service/.env
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    networks:
      - pettopia-network

  petcare-service:
    build:
      context: ./apps/petcare-service
      dockerfile: Dockerfile
    image: ${DOCKER_HUB}/pettopia-petcare-service:latest
    container_name: petcare-service
    env_file: apps/petcare-service/.env
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    networks:
      - pettopia-network

  # logging
  prometheus:
    image: prom/prometheus:v2.40.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      # Trỏ đến file config bạn sẽ tạo ở Bước 2
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - pettopia-network
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always

  loki:
    image: grafana/loki:2.7.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
    networks:
      - pettopia-network
    restart: always

  promtail:
    image: grafana/promtail:2.7.0
    container_name: promtail
    volumes:
      # Trỏ đến file config bạn sẽ tạo ở Bước 3
      - ./monitoring/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command:
      - "-config.file=/etc/promtail/promtail-config.yml"
    networks:
      - pettopia-network
    restart: always

  grafana:
    image: grafana/grafana:9.2.0
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
    networks:
      - pettopia-network
    restart: always
  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - pettopia-network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - pettopia-network
    restart: always
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    networks:
      - pettopia-network
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  pettopia-network:
    driver: bridge

volumes:
  kong_db_data:
  konga_data:
  prometheus_data:
  loki_data:
  grafana_data:
  redis_data:
