name: Build and Deploy Api-gateway Service

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "backend/apps/api-gateway/**"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Login Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. Build + Push image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/apps/api-gateway
          file: ./backend/apps/api-gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pettopia-api-gateway:latest

      # 3. SSH deploy to VPS
      - name: SSH to VPS & deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/pettopia/Pettopia/backend
            docker compose pull api-gateway
            docker compose up -d api-gateway
            docker image prune -f
